name: test run

on:
     workflow_call:
   

jobs:
    running:
        # name: walk
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - run: echo "job started"
            - run:  python3 app.py

    walking:
        needs: running
        runs-on: ubuntu-latest
        steps:
            - run: echo "job started"
            - run: echo "hello world evryone"
            - uses: actions/checkout@v6
              
            