name: test run

on:
    push: 
    workflow_dispatch:
   

jobs:
    running:
        # name: walk
        runs-on: ubuntu-latest
        steps:
            - run: echo "job started"
            - run: echo "hello world"
    walking:
        # name: walk
        runs-on: ubuntu-latest
        steps:
            - run: echo "job started"
            - run: echo "hello world"